### ISSUE TITLE
Unable to create transaction using Braintree pluging. 

### ISSUE THREAD

**Issue by atapatel** [BitBagCommerce/SyliusBraintreePlugin#8]
Hello there for sandbox envirnment everything is working perfectly fine but when it comes to production environment it gives below error in browser console log.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'toJSON')
    at i.getViewModel (braintree-dropin-internal.min.js:43:34051)
    at i.render (braintree-dropin-internal.min.js:43:34273)
    at i.setCurrentView (braintree-dropin-internal.min.js:43:52784)
    at i.showPaymentMethod (braintree-dropin-internal.min.js:43:29343)
    at i.execute (braintree-dropin-internal.min.js:1:16684)
    at Object.callback (braintree-dropin-internal.min.js:1:16537)
    at braintree-dropin-internal.min.js:1:19856
    at ke (braintree-dropin-internal.min.js:16:29896)
    at Function.vr (braintree-dropin-internal.min.js:16:49492)
    at e.History.loadUrl (braintree-dropin-internal.min.js:1:19797)
getViewModel @ braintree-dropin-internal.min.js:43
render @ braintree-dropin-internal.min.js:43
setCurrentView @ braintree-dropin-internal.min.js:43
showPaymentMethod @ braintree-dropin-internal.min.js:43
execute @ braintree-dropin-internal.min.js:1
(anonymous) @ braintree-dropin-internal.min.js:1
(anonymous) @ braintree-dropin-internal.min.js:1
ke @ braintree-dropin-internal.min.js:16
vr @ braintree-dropin-internal.min.js:16
loadUrl @ braintree-dropin-internal.min.js:1
navigate @ braintree-dropin-internal.min.js:43
c.receiveNewPaymentMethod @ braintree-dropin-internal.min.js:43
i @ braintree-dropin-internal.min.js:16
r._handleRequest @ braintree-dropin-internal.min.js:1
(anonymous) @ braintree-dropin-internal.min.js:1
r.receive @ braintree-dropin-internal.min.js:1
(anonymous) @ braintree-dropin-internal.min.js:1
```

**Comment by rust-le** [comment]
Most likely a problem with the plugin configuration. I'm closing this, if the problem persists, please create an issue
